/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GridConfig } from "./types/grid-config";
import { ComponentDefinition } from "./types/component-definition";
import { GridBuilderTheme } from "./types/theme";
import { GridBuilderPlugin } from "./types/plugin";
import { UIComponentOverrides } from "./types/ui-overrides";
import { GridItem, GridState } from "./services/state-manager";
export { GridConfig } from "./types/grid-config";
export { ComponentDefinition } from "./types/component-definition";
export { GridBuilderTheme } from "./types/theme";
export { GridBuilderPlugin } from "./types/plugin";
export { UIComponentOverrides } from "./types/ui-overrides";
export { GridItem, GridState } from "./services/state-manager";
export namespace Components {
    interface BlogApp {
    }
    interface BlogArticle {
        "author"?: string;
        /**
          * @default 'Article content goes here'
         */
        "content": string;
        "date"?: string;
    }
    interface BlogButton {
        "href"?: string;
        /**
          * @default 'Click me!'
         */
        "label": string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface BlogHeader {
        /**
          * @default 'Default Header'
         */
        "headerTitle": string;
        "subtitle"?: string;
    }
    /**
     * CanvasSection Component
     * =======================
     * Library component providing individual canvas dropzone.
     * **Tag**: `<canvas-section>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Reactivity**: Listens to gridState changes via StencilJS store
     */
    interface CanvasSection {
        /**
          * Canvas ID for state management  **Format**: 'canvas1', 'canvas2', etc. **Purpose**: Key for accessing canvas data in gridState.canvases **Required**: Component won't render without valid canvasId
         */
        "canvasId": string;
        /**
          * Component registry (from parent grid-builder)  **Source**: grid-builder component (built from components prop) **Structure**: Map<type, ComponentDefinition> **Purpose**: Pass to grid-item-wrapper for dynamic rendering
         */
        "componentRegistry"?: Map<string, ComponentDefinition>;
        /**
          * Grid configuration options  **Optional**: Customizes grid system behavior **Passed from**: grid-builder component **Used for**: Grid size calculations, constraints
         */
        "config"?: GridConfig;
    }
    /**
     * ComponentPalette Component
     * ===========================
     * Library component providing draggable component palette UI.
     * **Tag**: `<component-palette>`
     * **Shadow DOM**: Disabled (for consistency with other components)
     * **Reactivity**: Re-renders when components prop changes
     */
    interface ComponentPalette {
        /**
          * Component definitions to render in palette  **Required prop**: Array of ComponentDefinition objects **Source**: Passed from grid-builder component  **Each definition provides**: - type: Unique identifier for component - name: Display name in palette - icon: Visual identifier (emoji recommended) - defaultSize: Size when dropped (for drag clone sizing)  **Example**: ```typescript const components = [   {     type: 'header',     name: 'Header',     icon: '📄',     defaultSize: { width: 20, height: 8 },     render: ({ itemId, config }) => <my-header itemId={itemId} config={config} />   } ]; ```
         */
        "components": ComponentDefinition[];
        /**
          * Grid configuration options  **Optional prop**: Customizes grid system behavior **Passed from**: grid-builder component **Used for**: Drag clone sizing (gridToPixelsX/Y calculations)
         */
        "config"?: GridConfig;
    }
    /**
     * ConfigPanel Component
     * =====================
     * Library component providing configuration panel with auto-generated and custom forms.
     * **Tag**: `<config-panel>`
     * **Shadow DOM**: Disabled (for consistency with other components)
     */
    interface ConfigPanel {
        /**
          * Component registry (from parent grid-builder)  **Source**: grid-builder component **Purpose**: Look up component definitions for config forms
         */
        "componentRegistry"?: Map<string, ComponentDefinition>;
    }
    /**
     * Custom Drag Clone Component
     * ============================
     * Example custom drag clone that mimics a button component appearance.
     * This shows how to create a drag preview that looks exactly like the
     * component that will be dropped - helping with visual alignment.
     * The component fills the exact width and height provided, with no extra chrome.
     */
    interface CustomDragClone {
        /**
          * Component type being dragged
         */
        "componentType": string;
        /**
          * Height in pixels
         */
        "height": number;
        /**
          * Icon/emoji
         */
        "icon": string;
        /**
          * Display name
         */
        "name": string;
        /**
          * Width in pixels
         */
        "width": number;
    }
    /**
     * Custom Palette Item Component
     * ==============================
     * Example custom palette item that shows how consumers can create
     * fully customized palette entries for their components.
     */
    interface CustomPaletteItem {
        /**
          * Component type
         */
        "componentType": string;
        /**
          * Icon/emoji
         */
        "icon": string;
        /**
          * Display name
         */
        "name": string;
    }
    /**
     * GridBuilder Component
     * ======================
     * Main library component providing complete grid builder functionality.
     * **Tag**: `<grid-builder>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Reactivity**: Listens to gridState changes via StencilJS store
     */
    interface GridBuilder {
        /**
          * Component definitions registry  **Required prop**: Array of ComponentDefinition objects **Purpose**: Defines available component types (header, text, button, etc.)  **Each definition includes**: - type: Unique identifier (e.g., 'header', 'text-block') - name: Display name in palette - icon: Visual identifier (emoji recommended) - defaultSize: Initial size when dropped - render: Function returning component to render - configSchema: Optional auto-generated config form - renderConfigPanel: Optional custom config UI - Lifecycle hooks: onVisible, onHidden for virtual rendering  **Example**: ```typescript const components = [   {     type: 'header',     name: 'Header',     icon: '📄',     defaultSize: { width: 20, height: 8 },     render: ({ itemId, config }) => (       <my-header itemId={itemId} config={config} />     ),     configSchema: [       { name: 'text', label: 'Text', type: 'text', defaultValue: 'Header' }     ]   } ]; ```
         */
        "components": ComponentDefinition[];
        /**
          * Grid configuration options  **Optional prop**: Customizes grid system behavior **Default**: Standard 2% grid with 10px-50px constraints  **Configuration options**: - gridSizePercent: Grid unit as % of width (default: 2) - minGridSize: Minimum size in pixels (default: 10) - maxGridSize: Maximum size in pixels (default: 50) - snapToGrid: Enable snap-to-grid (default: true) - showGridLines: Show visual grid (default: true) - minItemSize: Minimum item dimensions (default: { width: 5, height: 4 }) - virtualRenderMargin: Pre-render margin (default: '20%')  **Example**: ```typescript const config = {   gridSizePercent: 3,           // 3% grid (33 units per 100%)   minGridSize: 15,              // 15px minimum   maxGridSize: 60,              // 60px maximum   snapToGrid: true,   virtualRenderMargin: '30%'    // Aggressive pre-loading }; ```
         */
        "config"?: GridConfig;
        /**
          * Initial state to restore  **Optional prop**: Restore saved layout **Purpose**: Load previously saved grid state  **State structure**: Same as gridState (canvases, viewport, etc.)  **Example**: ```typescript const savedState = JSON.parse(localStorage.getItem('grid-state')); <grid-builder initialState={savedState} ... /> ```
         */
        "initialState"?: Partial<GridState>;
        /**
          * Plugin instances for extending functionality  **Optional prop**: Array of GridBuilderPlugin instances **Purpose**: Add custom features, analytics, integrations  **Plugin lifecycle**: 1. Library calls plugin.init(api) on componentDidLoad 2. Plugin subscribes to events, adds UI, etc. 3. Library calls plugin.destroy() on disconnectedCallback  **Example**: ```typescript class AnalyticsPlugin implements GridBuilderPlugin {   name = 'analytics';    init(api: GridBuilderAPI) {     api.on('componentAdded', (e) => {       analytics.track('Component Added', { type: e.item.type });     });   }    destroy() {     // Cleanup   } }  const plugins = [new AnalyticsPlugin()]; ```
         */
        "plugins"?: GridBuilderPlugin[];
        /**
          * Visual theme customization  **Optional prop**: Customizes colors, fonts, and styling **Default**: Bootstrap-inspired blue theme  **Theme options**: - primaryColor: Accent color (default: '#007bff') - paletteBackground: Palette sidebar color (default: '#f5f5f5') - canvasBackground: Canvas background (default: '#ffffff') - gridLineColor: Grid line color (default: 'rgba(0,0,0,0.1)') - selectionColor: Selection outline (default: '#007bff') - resizeHandleColor: Resize handle color (default: '#007bff') - fontFamily: UI font (default: system font stack) - customProperties: CSS variables for advanced theming  **Example**: ```typescript const theme = {   primaryColor: '#ff6b6b',        // Brand red   paletteBackground: '#fff5f5',   // Light red   customProperties: {     '--text-color': '#ffffff',     '--border-radius': '8px'   } }; ```
         */
        "theme"?: GridBuilderTheme;
        /**
          * Custom UI component overrides  **Optional prop**: Replace default UI components **Purpose**: Fully customize visual appearance  **Overridable components**: - ConfigPanel: Configuration panel UI - ComponentPalette: Component palette sidebar - Toolbar: Top toolbar with controls  **Example**: ```typescript const uiOverrides = {   Toolbar: (props) => (     <div class="my-toolbar">       <button onClick={props.onUndo}>Undo</button>       <button onClick={props.onRedo}>Redo</button>     </div>   ) }; ```
         */
        "uiOverrides"?: UIComponentOverrides;
    }
    /**
     * GridItemWrapper Component
     * ==========================
     * Library component wrapping individual grid items with drag/resize/selection.
     * **Tag**: `<grid-item-wrapper>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Dynamic rendering**: Uses ComponentDefinition.render() from registry
     */
    interface GridItemWrapper {
        /**
          * Component registry (from parent grid-builder)  **Source**: grid-builder component (built from components prop) **Structure**: Map<type, ComponentDefinition> **Purpose**: Look up component definitions for dynamic rendering  **Note**: This is passed as a workaround since StencilJS doesn't have good support for context/provide-inject patterns. In a production app, consider using a global registry or context provider.
         */
        "componentRegistry"?: Map<string, ComponentDefinition>;
        /**
          * Grid configuration options  **Optional**: Customizes grid system behavior **Passed from**: grid-builder → canvas-section → grid-item-wrapper **Used for**: Grid size calculations with constraints
         */
        "config"?: GridConfig;
        /**
          * Grid item data (position, size, type, etc.)  **Source**: Parent canvas-section component **Contains**: id, canvasId, type, name, layouts (desktop/mobile), zIndex, config
         */
        "item": GridItem;
        /**
          * Render version (force re-render trigger)  **Source**: Parent canvas-section (incremented on resize) **Purpose**: Force grid calculation refresh when container resizes
         */
        "renderVersion"?: number;
    }
}
export interface BlogButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlogButtonElement;
}
declare global {
    interface HTMLBlogAppElement extends Components.BlogApp, HTMLStencilElement {
    }
    var HTMLBlogAppElement: {
        prototype: HTMLBlogAppElement;
        new (): HTMLBlogAppElement;
    };
    interface HTMLBlogArticleElement extends Components.BlogArticle, HTMLStencilElement {
    }
    var HTMLBlogArticleElement: {
        prototype: HTMLBlogArticleElement;
        new (): HTMLBlogArticleElement;
    };
    interface HTMLBlogButtonElementEventMap {
        "buttonClick": void;
    }
    interface HTMLBlogButtonElement extends Components.BlogButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBlogButtonElementEventMap>(type: K, listener: (this: HTMLBlogButtonElement, ev: BlogButtonCustomEvent<HTMLBlogButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBlogButtonElementEventMap>(type: K, listener: (this: HTMLBlogButtonElement, ev: BlogButtonCustomEvent<HTMLBlogButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBlogButtonElement: {
        prototype: HTMLBlogButtonElement;
        new (): HTMLBlogButtonElement;
    };
    interface HTMLBlogHeaderElement extends Components.BlogHeader, HTMLStencilElement {
    }
    var HTMLBlogHeaderElement: {
        prototype: HTMLBlogHeaderElement;
        new (): HTMLBlogHeaderElement;
    };
    /**
     * CanvasSection Component
     * =======================
     * Library component providing individual canvas dropzone.
     * **Tag**: `<canvas-section>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Reactivity**: Listens to gridState changes via StencilJS store
     */
    interface HTMLCanvasSectionElement extends Components.CanvasSection, HTMLStencilElement {
    }
    var HTMLCanvasSectionElement: {
        prototype: HTMLCanvasSectionElement;
        new (): HTMLCanvasSectionElement;
    };
    /**
     * ComponentPalette Component
     * ===========================
     * Library component providing draggable component palette UI.
     * **Tag**: `<component-palette>`
     * **Shadow DOM**: Disabled (for consistency with other components)
     * **Reactivity**: Re-renders when components prop changes
     */
    interface HTMLComponentPaletteElement extends Components.ComponentPalette, HTMLStencilElement {
    }
    var HTMLComponentPaletteElement: {
        prototype: HTMLComponentPaletteElement;
        new (): HTMLComponentPaletteElement;
    };
    /**
     * ConfigPanel Component
     * =====================
     * Library component providing configuration panel with auto-generated and custom forms.
     * **Tag**: `<config-panel>`
     * **Shadow DOM**: Disabled (for consistency with other components)
     */
    interface HTMLConfigPanelElement extends Components.ConfigPanel, HTMLStencilElement {
    }
    var HTMLConfigPanelElement: {
        prototype: HTMLConfigPanelElement;
        new (): HTMLConfigPanelElement;
    };
    /**
     * Custom Drag Clone Component
     * ============================
     * Example custom drag clone that mimics a button component appearance.
     * This shows how to create a drag preview that looks exactly like the
     * component that will be dropped - helping with visual alignment.
     * The component fills the exact width and height provided, with no extra chrome.
     */
    interface HTMLCustomDragCloneElement extends Components.CustomDragClone, HTMLStencilElement {
    }
    var HTMLCustomDragCloneElement: {
        prototype: HTMLCustomDragCloneElement;
        new (): HTMLCustomDragCloneElement;
    };
    /**
     * Custom Palette Item Component
     * ==============================
     * Example custom palette item that shows how consumers can create
     * fully customized palette entries for their components.
     */
    interface HTMLCustomPaletteItemElement extends Components.CustomPaletteItem, HTMLStencilElement {
    }
    var HTMLCustomPaletteItemElement: {
        prototype: HTMLCustomPaletteItemElement;
        new (): HTMLCustomPaletteItemElement;
    };
    /**
     * GridBuilder Component
     * ======================
     * Main library component providing complete grid builder functionality.
     * **Tag**: `<grid-builder>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Reactivity**: Listens to gridState changes via StencilJS store
     */
    interface HTMLGridBuilderElement extends Components.GridBuilder, HTMLStencilElement {
    }
    var HTMLGridBuilderElement: {
        prototype: HTMLGridBuilderElement;
        new (): HTMLGridBuilderElement;
    };
    /**
     * GridItemWrapper Component
     * ==========================
     * Library component wrapping individual grid items with drag/resize/selection.
     * **Tag**: `<grid-item-wrapper>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Dynamic rendering**: Uses ComponentDefinition.render() from registry
     */
    interface HTMLGridItemWrapperElement extends Components.GridItemWrapper, HTMLStencilElement {
    }
    var HTMLGridItemWrapperElement: {
        prototype: HTMLGridItemWrapperElement;
        new (): HTMLGridItemWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "blog-app": HTMLBlogAppElement;
        "blog-article": HTMLBlogArticleElement;
        "blog-button": HTMLBlogButtonElement;
        "blog-header": HTMLBlogHeaderElement;
        "canvas-section": HTMLCanvasSectionElement;
        "component-palette": HTMLComponentPaletteElement;
        "config-panel": HTMLConfigPanelElement;
        "custom-drag-clone": HTMLCustomDragCloneElement;
        "custom-palette-item": HTMLCustomPaletteItemElement;
        "grid-builder": HTMLGridBuilderElement;
        "grid-item-wrapper": HTMLGridItemWrapperElement;
    }
}
declare namespace LocalJSX {
    interface BlogApp {
    }
    interface BlogArticle {
        "author"?: string;
        /**
          * @default 'Article content goes here'
         */
        "content"?: string;
        "date"?: string;
    }
    interface BlogButton {
        "href"?: string;
        /**
          * @default 'Click me!'
         */
        "label"?: string;
        "onButtonClick"?: (event: BlogButtonCustomEvent<void>) => void;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface BlogHeader {
        /**
          * @default 'Default Header'
         */
        "headerTitle"?: string;
        "subtitle"?: string;
    }
    /**
     * CanvasSection Component
     * =======================
     * Library component providing individual canvas dropzone.
     * **Tag**: `<canvas-section>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Reactivity**: Listens to gridState changes via StencilJS store
     */
    interface CanvasSection {
        /**
          * Canvas ID for state management  **Format**: 'canvas1', 'canvas2', etc. **Purpose**: Key for accessing canvas data in gridState.canvases **Required**: Component won't render without valid canvasId
         */
        "canvasId": string;
        /**
          * Component registry (from parent grid-builder)  **Source**: grid-builder component (built from components prop) **Structure**: Map<type, ComponentDefinition> **Purpose**: Pass to grid-item-wrapper for dynamic rendering
         */
        "componentRegistry"?: Map<string, ComponentDefinition>;
        /**
          * Grid configuration options  **Optional**: Customizes grid system behavior **Passed from**: grid-builder component **Used for**: Grid size calculations, constraints
         */
        "config"?: GridConfig;
    }
    /**
     * ComponentPalette Component
     * ===========================
     * Library component providing draggable component palette UI.
     * **Tag**: `<component-palette>`
     * **Shadow DOM**: Disabled (for consistency with other components)
     * **Reactivity**: Re-renders when components prop changes
     */
    interface ComponentPalette {
        /**
          * Component definitions to render in palette  **Required prop**: Array of ComponentDefinition objects **Source**: Passed from grid-builder component  **Each definition provides**: - type: Unique identifier for component - name: Display name in palette - icon: Visual identifier (emoji recommended) - defaultSize: Size when dropped (for drag clone sizing)  **Example**: ```typescript const components = [   {     type: 'header',     name: 'Header',     icon: '📄',     defaultSize: { width: 20, height: 8 },     render: ({ itemId, config }) => <my-header itemId={itemId} config={config} />   } ]; ```
         */
        "components": ComponentDefinition[];
        /**
          * Grid configuration options  **Optional prop**: Customizes grid system behavior **Passed from**: grid-builder component **Used for**: Drag clone sizing (gridToPixelsX/Y calculations)
         */
        "config"?: GridConfig;
    }
    /**
     * ConfigPanel Component
     * =====================
     * Library component providing configuration panel with auto-generated and custom forms.
     * **Tag**: `<config-panel>`
     * **Shadow DOM**: Disabled (for consistency with other components)
     */
    interface ConfigPanel {
        /**
          * Component registry (from parent grid-builder)  **Source**: grid-builder component **Purpose**: Look up component definitions for config forms
         */
        "componentRegistry"?: Map<string, ComponentDefinition>;
    }
    /**
     * Custom Drag Clone Component
     * ============================
     * Example custom drag clone that mimics a button component appearance.
     * This shows how to create a drag preview that looks exactly like the
     * component that will be dropped - helping with visual alignment.
     * The component fills the exact width and height provided, with no extra chrome.
     */
    interface CustomDragClone {
        /**
          * Component type being dragged
         */
        "componentType": string;
        /**
          * Height in pixels
         */
        "height": number;
        /**
          * Icon/emoji
         */
        "icon": string;
        /**
          * Display name
         */
        "name": string;
        /**
          * Width in pixels
         */
        "width": number;
    }
    /**
     * Custom Palette Item Component
     * ==============================
     * Example custom palette item that shows how consumers can create
     * fully customized palette entries for their components.
     */
    interface CustomPaletteItem {
        /**
          * Component type
         */
        "componentType": string;
        /**
          * Icon/emoji
         */
        "icon": string;
        /**
          * Display name
         */
        "name": string;
    }
    /**
     * GridBuilder Component
     * ======================
     * Main library component providing complete grid builder functionality.
     * **Tag**: `<grid-builder>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Reactivity**: Listens to gridState changes via StencilJS store
     */
    interface GridBuilder {
        /**
          * Component definitions registry  **Required prop**: Array of ComponentDefinition objects **Purpose**: Defines available component types (header, text, button, etc.)  **Each definition includes**: - type: Unique identifier (e.g., 'header', 'text-block') - name: Display name in palette - icon: Visual identifier (emoji recommended) - defaultSize: Initial size when dropped - render: Function returning component to render - configSchema: Optional auto-generated config form - renderConfigPanel: Optional custom config UI - Lifecycle hooks: onVisible, onHidden for virtual rendering  **Example**: ```typescript const components = [   {     type: 'header',     name: 'Header',     icon: '📄',     defaultSize: { width: 20, height: 8 },     render: ({ itemId, config }) => (       <my-header itemId={itemId} config={config} />     ),     configSchema: [       { name: 'text', label: 'Text', type: 'text', defaultValue: 'Header' }     ]   } ]; ```
         */
        "components": ComponentDefinition[];
        /**
          * Grid configuration options  **Optional prop**: Customizes grid system behavior **Default**: Standard 2% grid with 10px-50px constraints  **Configuration options**: - gridSizePercent: Grid unit as % of width (default: 2) - minGridSize: Minimum size in pixels (default: 10) - maxGridSize: Maximum size in pixels (default: 50) - snapToGrid: Enable snap-to-grid (default: true) - showGridLines: Show visual grid (default: true) - minItemSize: Minimum item dimensions (default: { width: 5, height: 4 }) - virtualRenderMargin: Pre-render margin (default: '20%')  **Example**: ```typescript const config = {   gridSizePercent: 3,           // 3% grid (33 units per 100%)   minGridSize: 15,              // 15px minimum   maxGridSize: 60,              // 60px maximum   snapToGrid: true,   virtualRenderMargin: '30%'    // Aggressive pre-loading }; ```
         */
        "config"?: GridConfig;
        /**
          * Initial state to restore  **Optional prop**: Restore saved layout **Purpose**: Load previously saved grid state  **State structure**: Same as gridState (canvases, viewport, etc.)  **Example**: ```typescript const savedState = JSON.parse(localStorage.getItem('grid-state')); <grid-builder initialState={savedState} ... /> ```
         */
        "initialState"?: Partial<GridState>;
        /**
          * Plugin instances for extending functionality  **Optional prop**: Array of GridBuilderPlugin instances **Purpose**: Add custom features, analytics, integrations  **Plugin lifecycle**: 1. Library calls plugin.init(api) on componentDidLoad 2. Plugin subscribes to events, adds UI, etc. 3. Library calls plugin.destroy() on disconnectedCallback  **Example**: ```typescript class AnalyticsPlugin implements GridBuilderPlugin {   name = 'analytics';    init(api: GridBuilderAPI) {     api.on('componentAdded', (e) => {       analytics.track('Component Added', { type: e.item.type });     });   }    destroy() {     // Cleanup   } }  const plugins = [new AnalyticsPlugin()]; ```
         */
        "plugins"?: GridBuilderPlugin[];
        /**
          * Visual theme customization  **Optional prop**: Customizes colors, fonts, and styling **Default**: Bootstrap-inspired blue theme  **Theme options**: - primaryColor: Accent color (default: '#007bff') - paletteBackground: Palette sidebar color (default: '#f5f5f5') - canvasBackground: Canvas background (default: '#ffffff') - gridLineColor: Grid line color (default: 'rgba(0,0,0,0.1)') - selectionColor: Selection outline (default: '#007bff') - resizeHandleColor: Resize handle color (default: '#007bff') - fontFamily: UI font (default: system font stack) - customProperties: CSS variables for advanced theming  **Example**: ```typescript const theme = {   primaryColor: '#ff6b6b',        // Brand red   paletteBackground: '#fff5f5',   // Light red   customProperties: {     '--text-color': '#ffffff',     '--border-radius': '8px'   } }; ```
         */
        "theme"?: GridBuilderTheme;
        /**
          * Custom UI component overrides  **Optional prop**: Replace default UI components **Purpose**: Fully customize visual appearance  **Overridable components**: - ConfigPanel: Configuration panel UI - ComponentPalette: Component palette sidebar - Toolbar: Top toolbar with controls  **Example**: ```typescript const uiOverrides = {   Toolbar: (props) => (     <div class="my-toolbar">       <button onClick={props.onUndo}>Undo</button>       <button onClick={props.onRedo}>Redo</button>     </div>   ) }; ```
         */
        "uiOverrides"?: UIComponentOverrides;
    }
    /**
     * GridItemWrapper Component
     * ==========================
     * Library component wrapping individual grid items with drag/resize/selection.
     * **Tag**: `<grid-item-wrapper>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Dynamic rendering**: Uses ComponentDefinition.render() from registry
     */
    interface GridItemWrapper {
        /**
          * Component registry (from parent grid-builder)  **Source**: grid-builder component (built from components prop) **Structure**: Map<type, ComponentDefinition> **Purpose**: Look up component definitions for dynamic rendering  **Note**: This is passed as a workaround since StencilJS doesn't have good support for context/provide-inject patterns. In a production app, consider using a global registry or context provider.
         */
        "componentRegistry"?: Map<string, ComponentDefinition>;
        /**
          * Grid configuration options  **Optional**: Customizes grid system behavior **Passed from**: grid-builder → canvas-section → grid-item-wrapper **Used for**: Grid size calculations with constraints
         */
        "config"?: GridConfig;
        /**
          * Grid item data (position, size, type, etc.)  **Source**: Parent canvas-section component **Contains**: id, canvasId, type, name, layouts (desktop/mobile), zIndex, config
         */
        "item": GridItem;
        /**
          * Render version (force re-render trigger)  **Source**: Parent canvas-section (incremented on resize) **Purpose**: Force grid calculation refresh when container resizes
         */
        "renderVersion"?: number;
    }
    interface IntrinsicElements {
        "blog-app": BlogApp;
        "blog-article": BlogArticle;
        "blog-button": BlogButton;
        "blog-header": BlogHeader;
        "canvas-section": CanvasSection;
        "component-palette": ComponentPalette;
        "config-panel": ConfigPanel;
        "custom-drag-clone": CustomDragClone;
        "custom-palette-item": CustomPaletteItem;
        "grid-builder": GridBuilder;
        "grid-item-wrapper": GridItemWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blog-app": LocalJSX.BlogApp & JSXBase.HTMLAttributes<HTMLBlogAppElement>;
            "blog-article": LocalJSX.BlogArticle & JSXBase.HTMLAttributes<HTMLBlogArticleElement>;
            "blog-button": LocalJSX.BlogButton & JSXBase.HTMLAttributes<HTMLBlogButtonElement>;
            "blog-header": LocalJSX.BlogHeader & JSXBase.HTMLAttributes<HTMLBlogHeaderElement>;
            /**
             * CanvasSection Component
             * =======================
             * Library component providing individual canvas dropzone.
             * **Tag**: `<canvas-section>`
             * **Shadow DOM**: Disabled (required for interact.js compatibility)
             * **Reactivity**: Listens to gridState changes via StencilJS store
             */
            "canvas-section": LocalJSX.CanvasSection & JSXBase.HTMLAttributes<HTMLCanvasSectionElement>;
            /**
             * ComponentPalette Component
             * ===========================
             * Library component providing draggable component palette UI.
             * **Tag**: `<component-palette>`
             * **Shadow DOM**: Disabled (for consistency with other components)
             * **Reactivity**: Re-renders when components prop changes
             */
            "component-palette": LocalJSX.ComponentPalette & JSXBase.HTMLAttributes<HTMLComponentPaletteElement>;
            /**
             * ConfigPanel Component
             * =====================
             * Library component providing configuration panel with auto-generated and custom forms.
             * **Tag**: `<config-panel>`
             * **Shadow DOM**: Disabled (for consistency with other components)
             */
            "config-panel": LocalJSX.ConfigPanel & JSXBase.HTMLAttributes<HTMLConfigPanelElement>;
            /**
             * Custom Drag Clone Component
             * ============================
             * Example custom drag clone that mimics a button component appearance.
             * This shows how to create a drag preview that looks exactly like the
             * component that will be dropped - helping with visual alignment.
             * The component fills the exact width and height provided, with no extra chrome.
             */
            "custom-drag-clone": LocalJSX.CustomDragClone & JSXBase.HTMLAttributes<HTMLCustomDragCloneElement>;
            /**
             * Custom Palette Item Component
             * ==============================
             * Example custom palette item that shows how consumers can create
             * fully customized palette entries for their components.
             */
            "custom-palette-item": LocalJSX.CustomPaletteItem & JSXBase.HTMLAttributes<HTMLCustomPaletteItemElement>;
            /**
             * GridBuilder Component
             * ======================
             * Main library component providing complete grid builder functionality.
             * **Tag**: `<grid-builder>`
             * **Shadow DOM**: Disabled (required for interact.js compatibility)
             * **Reactivity**: Listens to gridState changes via StencilJS store
             */
            "grid-builder": LocalJSX.GridBuilder & JSXBase.HTMLAttributes<HTMLGridBuilderElement>;
            /**
             * GridItemWrapper Component
             * ==========================
             * Library component wrapping individual grid items with drag/resize/selection.
             * **Tag**: `<grid-item-wrapper>`
             * **Shadow DOM**: Disabled (required for interact.js compatibility)
             * **Dynamic rendering**: Uses ComponentDefinition.render() from registry
             */
            "grid-item-wrapper": LocalJSX.GridItemWrapper & JSXBase.HTMLAttributes<HTMLGridItemWrapperElement>;
        }
    }
}
