import { html } from 'lit-html';
import { createElement } from 'react';
import { Description } from '@storybook/addon-docs';
import _ from 'lodash';

import './global.scss';

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: { expanded: true },
  options: {
    storySort: (storyA, storyB) => {
      // Simple alphabetical sorting by title
      const titleA = storyA.title.toLowerCase();
      const titleB = storyB.title.toLowerCase();
      return titleA.localeCompare(titleB, undefined, { numeric: true });
    }
  },

  /** Customize docs page to embed component docs generated by Stencil */
  docs: {
    extractComponentDescription: (_component, { readme }) => readme,
    page: () => createElement(Description),
  },
}

/**
 * Custom decorators:
 *
 * - Add story wrapper for styling based on component name and story name
 *
 *   <div class="story-wrapper grid-builder-story basic-usage">${story content}</div>
 */
export const decorators = [(story, meta) => {
  const component = meta.component ?? meta.componentId;
  const storySpecificCls = [`${component}-story`, meta.name].map(_.kebabCase).join(' ');

  return html`<div class="story-wrapper ${storySpecificCls}">${story()}</div>`;
}]
