/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GridItem } from "./services/state-manager";
export { GridItem } from "./services/state-manager";
export namespace Components {
    /**
     * CanvasSection Component
     * =======================
     * StencilJS component providing individual canvas dropzone with item management.
     * **Tag**: `<canvas-section>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
     */
    interface CanvasSection {
        /**
          * Canvas ID for state management  **Format**: 'canvas1', 'canvas2', etc. **Purpose**: Key for accessing canvas data in gridState.canvases **Required**: Component won't render without valid canvasId
         */
        "canvasId": string;
        /**
          * Section number for UI display  **Format**: 1, 2, 3, etc. **Purpose**: User-facing label ("Section 1", "Section 2") **Decoupled from canvasId**: Allows reordering without breaking state
         */
        "sectionNumber": number;
    }
    interface ComponentButton {
        "itemId": string;
    }
    interface ComponentDashboardWidget {
        "itemId": string;
    }
    interface ComponentHeader {
        "itemId": string;
    }
    interface ComponentImage {
        "itemId": string;
    }
    interface ComponentImageGallery {
        "itemId": string;
    }
    interface ComponentLiveData {
        "itemId": string;
    }
    /**
     * ComponentPalette Component
     * ===========================
     * StencilJS component providing draggable component library UI.
     * **Tag**: `<component-palette>`
     * **Shadow DOM**: Disabled (integrates with global styles)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render)
     */
    interface ComponentPalette {
    }
    interface ComponentTextBlock {
        "itemId": string;
    }
    interface ComponentVideo {
        "itemId": string;
    }
    interface ConfigPanel {
    }
    interface GridBuilderApp {
    }
    /**
     * GridItemWrapper Component
     * ==========================
     * StencilJS component wrapping individual grid items with drag/resize/selection.
     * **Tag**: `<grid-item-wrapper>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
     */
    interface GridItemWrapper {
        /**
          * Grid item data (position, size, type, etc.)  **Source**: Parent canvas-section component **Contains**: id, canvasId, type, name, layouts (desktop/mobile), zIndex **Updates**: Trigger re-render and grid calculations
         */
        "item": GridItem;
        /**
          * Render version (force re-render trigger)  **Source**: Parent canvas-section (incremented on resize) **Purpose**: Force grid calculation refresh when container resizes **Optional**: Defaults to undefined  **Why needed**: - Grid calculations cached based on container width - Container resize invalidates cache - Parent increments renderVersion → wrapper recalculates
         */
        "renderVersion"?: number;
    }
}
declare global {
    /**
     * CanvasSection Component
     * =======================
     * StencilJS component providing individual canvas dropzone with item management.
     * **Tag**: `<canvas-section>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
     */
    interface HTMLCanvasSectionElement extends Components.CanvasSection, HTMLStencilElement {
    }
    var HTMLCanvasSectionElement: {
        prototype: HTMLCanvasSectionElement;
        new (): HTMLCanvasSectionElement;
    };
    interface HTMLComponentButtonElement extends Components.ComponentButton, HTMLStencilElement {
    }
    var HTMLComponentButtonElement: {
        prototype: HTMLComponentButtonElement;
        new (): HTMLComponentButtonElement;
    };
    interface HTMLComponentDashboardWidgetElement extends Components.ComponentDashboardWidget, HTMLStencilElement {
    }
    var HTMLComponentDashboardWidgetElement: {
        prototype: HTMLComponentDashboardWidgetElement;
        new (): HTMLComponentDashboardWidgetElement;
    };
    interface HTMLComponentHeaderElement extends Components.ComponentHeader, HTMLStencilElement {
    }
    var HTMLComponentHeaderElement: {
        prototype: HTMLComponentHeaderElement;
        new (): HTMLComponentHeaderElement;
    };
    interface HTMLComponentImageElement extends Components.ComponentImage, HTMLStencilElement {
    }
    var HTMLComponentImageElement: {
        prototype: HTMLComponentImageElement;
        new (): HTMLComponentImageElement;
    };
    interface HTMLComponentImageGalleryElement extends Components.ComponentImageGallery, HTMLStencilElement {
    }
    var HTMLComponentImageGalleryElement: {
        prototype: HTMLComponentImageGalleryElement;
        new (): HTMLComponentImageGalleryElement;
    };
    interface HTMLComponentLiveDataElement extends Components.ComponentLiveData, HTMLStencilElement {
    }
    var HTMLComponentLiveDataElement: {
        prototype: HTMLComponentLiveDataElement;
        new (): HTMLComponentLiveDataElement;
    };
    /**
     * ComponentPalette Component
     * ===========================
     * StencilJS component providing draggable component library UI.
     * **Tag**: `<component-palette>`
     * **Shadow DOM**: Disabled (integrates with global styles)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render)
     */
    interface HTMLComponentPaletteElement extends Components.ComponentPalette, HTMLStencilElement {
    }
    var HTMLComponentPaletteElement: {
        prototype: HTMLComponentPaletteElement;
        new (): HTMLComponentPaletteElement;
    };
    interface HTMLComponentTextBlockElement extends Components.ComponentTextBlock, HTMLStencilElement {
    }
    var HTMLComponentTextBlockElement: {
        prototype: HTMLComponentTextBlockElement;
        new (): HTMLComponentTextBlockElement;
    };
    interface HTMLComponentVideoElement extends Components.ComponentVideo, HTMLStencilElement {
    }
    var HTMLComponentVideoElement: {
        prototype: HTMLComponentVideoElement;
        new (): HTMLComponentVideoElement;
    };
    interface HTMLConfigPanelElement extends Components.ConfigPanel, HTMLStencilElement {
    }
    var HTMLConfigPanelElement: {
        prototype: HTMLConfigPanelElement;
        new (): HTMLConfigPanelElement;
    };
    interface HTMLGridBuilderAppElement extends Components.GridBuilderApp, HTMLStencilElement {
    }
    var HTMLGridBuilderAppElement: {
        prototype: HTMLGridBuilderAppElement;
        new (): HTMLGridBuilderAppElement;
    };
    /**
     * GridItemWrapper Component
     * ==========================
     * StencilJS component wrapping individual grid items with drag/resize/selection.
     * **Tag**: `<grid-item-wrapper>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
     */
    interface HTMLGridItemWrapperElement extends Components.GridItemWrapper, HTMLStencilElement {
    }
    var HTMLGridItemWrapperElement: {
        prototype: HTMLGridItemWrapperElement;
        new (): HTMLGridItemWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "canvas-section": HTMLCanvasSectionElement;
        "component-button": HTMLComponentButtonElement;
        "component-dashboard-widget": HTMLComponentDashboardWidgetElement;
        "component-header": HTMLComponentHeaderElement;
        "component-image": HTMLComponentImageElement;
        "component-image-gallery": HTMLComponentImageGalleryElement;
        "component-live-data": HTMLComponentLiveDataElement;
        "component-palette": HTMLComponentPaletteElement;
        "component-text-block": HTMLComponentTextBlockElement;
        "component-video": HTMLComponentVideoElement;
        "config-panel": HTMLConfigPanelElement;
        "grid-builder-app": HTMLGridBuilderAppElement;
        "grid-item-wrapper": HTMLGridItemWrapperElement;
    }
}
declare namespace LocalJSX {
    /**
     * CanvasSection Component
     * =======================
     * StencilJS component providing individual canvas dropzone with item management.
     * **Tag**: `<canvas-section>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
     */
    interface CanvasSection {
        /**
          * Canvas ID for state management  **Format**: 'canvas1', 'canvas2', etc. **Purpose**: Key for accessing canvas data in gridState.canvases **Required**: Component won't render without valid canvasId
         */
        "canvasId": string;
        /**
          * Section number for UI display  **Format**: 1, 2, 3, etc. **Purpose**: User-facing label ("Section 1", "Section 2") **Decoupled from canvasId**: Allows reordering without breaking state
         */
        "sectionNumber": number;
    }
    interface ComponentButton {
        "itemId": string;
    }
    interface ComponentDashboardWidget {
        "itemId": string;
    }
    interface ComponentHeader {
        "itemId": string;
    }
    interface ComponentImage {
        "itemId": string;
    }
    interface ComponentImageGallery {
        "itemId": string;
    }
    interface ComponentLiveData {
        "itemId": string;
    }
    /**
     * ComponentPalette Component
     * ===========================
     * StencilJS component providing draggable component library UI.
     * **Tag**: `<component-palette>`
     * **Shadow DOM**: Disabled (integrates with global styles)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render)
     */
    interface ComponentPalette {
    }
    interface ComponentTextBlock {
        "itemId": string;
    }
    interface ComponentVideo {
        "itemId": string;
    }
    interface ConfigPanel {
    }
    interface GridBuilderApp {
    }
    /**
     * GridItemWrapper Component
     * ==========================
     * StencilJS component wrapping individual grid items with drag/resize/selection.
     * **Tag**: `<grid-item-wrapper>`
     * **Shadow DOM**: Disabled (required for interact.js compatibility)
     * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
     */
    interface GridItemWrapper {
        /**
          * Grid item data (position, size, type, etc.)  **Source**: Parent canvas-section component **Contains**: id, canvasId, type, name, layouts (desktop/mobile), zIndex **Updates**: Trigger re-render and grid calculations
         */
        "item": GridItem;
        /**
          * Render version (force re-render trigger)  **Source**: Parent canvas-section (incremented on resize) **Purpose**: Force grid calculation refresh when container resizes **Optional**: Defaults to undefined  **Why needed**: - Grid calculations cached based on container width - Container resize invalidates cache - Parent increments renderVersion → wrapper recalculates
         */
        "renderVersion"?: number;
    }
    interface IntrinsicElements {
        "canvas-section": CanvasSection;
        "component-button": ComponentButton;
        "component-dashboard-widget": ComponentDashboardWidget;
        "component-header": ComponentHeader;
        "component-image": ComponentImage;
        "component-image-gallery": ComponentImageGallery;
        "component-live-data": ComponentLiveData;
        "component-palette": ComponentPalette;
        "component-text-block": ComponentTextBlock;
        "component-video": ComponentVideo;
        "config-panel": ConfigPanel;
        "grid-builder-app": GridBuilderApp;
        "grid-item-wrapper": GridItemWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * CanvasSection Component
             * =======================
             * StencilJS component providing individual canvas dropzone with item management.
             * **Tag**: `<canvas-section>`
             * **Shadow DOM**: Disabled (required for interact.js compatibility)
             * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
             */
            "canvas-section": LocalJSX.CanvasSection & JSXBase.HTMLAttributes<HTMLCanvasSectionElement>;
            "component-button": LocalJSX.ComponentButton & JSXBase.HTMLAttributes<HTMLComponentButtonElement>;
            "component-dashboard-widget": LocalJSX.ComponentDashboardWidget & JSXBase.HTMLAttributes<HTMLComponentDashboardWidgetElement>;
            "component-header": LocalJSX.ComponentHeader & JSXBase.HTMLAttributes<HTMLComponentHeaderElement>;
            "component-image": LocalJSX.ComponentImage & JSXBase.HTMLAttributes<HTMLComponentImageElement>;
            "component-image-gallery": LocalJSX.ComponentImageGallery & JSXBase.HTMLAttributes<HTMLComponentImageGalleryElement>;
            "component-live-data": LocalJSX.ComponentLiveData & JSXBase.HTMLAttributes<HTMLComponentLiveDataElement>;
            /**
             * ComponentPalette Component
             * ===========================
             * StencilJS component providing draggable component library UI.
             * **Tag**: `<component-palette>`
             * **Shadow DOM**: Disabled (integrates with global styles)
             * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render)
             */
            "component-palette": LocalJSX.ComponentPalette & JSXBase.HTMLAttributes<HTMLComponentPaletteElement>;
            "component-text-block": LocalJSX.ComponentTextBlock & JSXBase.HTMLAttributes<HTMLComponentTextBlockElement>;
            "component-video": LocalJSX.ComponentVideo & JSXBase.HTMLAttributes<HTMLComponentVideoElement>;
            "config-panel": LocalJSX.ConfigPanel & JSXBase.HTMLAttributes<HTMLConfigPanelElement>;
            "grid-builder-app": LocalJSX.GridBuilderApp & JSXBase.HTMLAttributes<HTMLGridBuilderAppElement>;
            /**
             * GridItemWrapper Component
             * ==========================
             * StencilJS component wrapping individual grid items with drag/resize/selection.
             * **Tag**: `<grid-item-wrapper>`
             * **Shadow DOM**: Disabled (required for interact.js compatibility)
             * **Lifecycle**: Standard StencilJS (componentWillLoad → componentDidLoad → render → disconnectedCallback)
             */
            "grid-item-wrapper": LocalJSX.GridItemWrapper & JSXBase.HTMLAttributes<HTMLGridItemWrapperElement>;
        }
    }
}
