/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GridItem } from "./services/state-manager";
export { GridItem } from "./services/state-manager";
export namespace Components {
    interface CanvasSection {
        "canvasId": string;
        "sectionNumber": number;
    }
    interface ComponentPalette {
    }
    interface ConfigPanel {
    }
    interface GridBuilderApp {
    }
    interface GridItemWrapper {
        "item": GridItem;
    }
}
declare global {
    interface HTMLCanvasSectionElement extends Components.CanvasSection, HTMLStencilElement {
    }
    var HTMLCanvasSectionElement: {
        prototype: HTMLCanvasSectionElement;
        new (): HTMLCanvasSectionElement;
    };
    interface HTMLComponentPaletteElement extends Components.ComponentPalette, HTMLStencilElement {
    }
    var HTMLComponentPaletteElement: {
        prototype: HTMLComponentPaletteElement;
        new (): HTMLComponentPaletteElement;
    };
    interface HTMLConfigPanelElement extends Components.ConfigPanel, HTMLStencilElement {
    }
    var HTMLConfigPanelElement: {
        prototype: HTMLConfigPanelElement;
        new (): HTMLConfigPanelElement;
    };
    interface HTMLGridBuilderAppElement extends Components.GridBuilderApp, HTMLStencilElement {
    }
    var HTMLGridBuilderAppElement: {
        prototype: HTMLGridBuilderAppElement;
        new (): HTMLGridBuilderAppElement;
    };
    interface HTMLGridItemWrapperElement extends Components.GridItemWrapper, HTMLStencilElement {
    }
    var HTMLGridItemWrapperElement: {
        prototype: HTMLGridItemWrapperElement;
        new (): HTMLGridItemWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "canvas-section": HTMLCanvasSectionElement;
        "component-palette": HTMLComponentPaletteElement;
        "config-panel": HTMLConfigPanelElement;
        "grid-builder-app": HTMLGridBuilderAppElement;
        "grid-item-wrapper": HTMLGridItemWrapperElement;
    }
}
declare namespace LocalJSX {
    interface CanvasSection {
        "canvasId": string;
        "sectionNumber": number;
    }
    interface ComponentPalette {
    }
    interface ConfigPanel {
    }
    interface GridBuilderApp {
    }
    interface GridItemWrapper {
        "item": GridItem;
    }
    interface IntrinsicElements {
        "canvas-section": CanvasSection;
        "component-palette": ComponentPalette;
        "config-panel": ConfigPanel;
        "grid-builder-app": GridBuilderApp;
        "grid-item-wrapper": GridItemWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "canvas-section": LocalJSX.CanvasSection & JSXBase.HTMLAttributes<HTMLCanvasSectionElement>;
            "component-palette": LocalJSX.ComponentPalette & JSXBase.HTMLAttributes<HTMLComponentPaletteElement>;
            "config-panel": LocalJSX.ConfigPanel & JSXBase.HTMLAttributes<HTMLConfigPanelElement>;
            "grid-builder-app": LocalJSX.GridBuilderApp & JSXBase.HTMLAttributes<HTMLGridBuilderAppElement>;
            "grid-item-wrapper": LocalJSX.GridItemWrapper & JSXBase.HTMLAttributes<HTMLGridItemWrapperElement>;
        }
    }
}
